### ISSUE TITLE
Reference to blog

### ISSUE THREAD

**Issue by rladstaetter** [joan38/socialnetwork#1]
A top level link to your blog post would be fine (readme).

I starred your github project but can't find your blog entry anymore (maybe you mention it somwhere in the code though)

**Comment by pierangeloc** [comment]
https://itnext.io/a-cqrs-approach-with-kafka-streams-and-scala-49bfa78e4295

**Comment by joan38** [comment]
Thanks guys and sorry for the missing readme. I fixed it now.
